export const sharedGlobalConstants = {
    dashboard: false,
    master_of_master: false,
    trip: false,
    trip_cost: false,
    trip_settlement: false,
    tyre_settlement: false,
    other_settlement: false,
    consignments: false,
    vehicle: false,
    maintenance: false,
    drivers: false,
    driversLeave: false,
    users: false,
    clients: false,
    accounting: false,
    demandview: false,
    manufacturer: false,
    brand: false,
    productLog: false,
    chassis: false,
    stock: false,
    scrap: false,
    resaleToBuyer: false,
    issueReceive: false,
    locations: false,
    geofence: false,
    materials: false,
    regions: false,
    routes: false,
    offices: false,
    documents: false,
    corridor: false,
    other_cost_master: false,
    spare_part: false,
    spare_part_brand: false,
    spare_part_master: false,
    spare_part_master_type: false,
    vehicle_master: false,
    vehicle_application: false,
    vehicle_model: false,
    vehicle_due_master: false,
    vehicle_transaction: false,
    vehicle_profile: false,
    vehicle_cost: false,
    vehicle_cost_master: false,
    rate_master: false,
    taxes: false,
    driver_cost: false,
    fuel_cost: false,
    vehicle_due: false,
    maintenance_spare_part_type_master: false,
    maintenance_spare_part_master: false,
    maintenance_spare_part: false,
    notifications: false,
    maintenance_vehicle_service: false,
    maintenance_vehicle_service_task: false,
    pageHeaderTitle: 'Dashboard',
    driverHeaderTitle: 'Drivers',
    trip_cost_master: false,
    alerts: false,
    branches: false,
    bills: false,
    ledgers: false,
    trip_payable: false,
    consignments_bill: null,
    vehicleCostId: null,
    tyreCostId: null,
    voucherId: null,
    tyreId: null,
    otherSettlementId: null,
    tripSettlementId: null,
    fuelCostId: null,
    help_and_support: false,
    reporting: false,
    fuel_consumption: false,
    events: false,
    unused_vehicles: false,
    displaySplash: false,
    vehicle_tracing : false,
    api_settings : false, 
};
export const activeToggleConstants = { 
    am_track: false,
    am_plan: false,
    am_analyze: false,
    am_trip: false,
    company_profile: false,
    fm_plan: false,
    fm_track: false,
    consignor: false,
    consignee: false,
    vendor: false,
    fuel_rates: false,
    rate_card: false,
    contract: false,
    manufacturer: false,
    brand: false,
    productLog: false,
    chassis: false,
    stock: false,
    scrap: false,
    resaleToBuyer: false,
    issueReceive: false,
    trip: false,
    locations: false,
    geofence: false,
    materials: false,
    offices: false,
    corridor: false,
    am_help_and_support: false,
    fm_help_and_support: false,
    branches: false,
    vehicle: false,
    drivers: false,
    users: false,
    mm_service_stations: false,
    mm_service: false,
    service_history:false,
    reminders:false,
    book_services:false,
    vehicle_tracing :false,
    spare_inventory :false,
    spare_overview :false,
    track_maintenance_manager:false,
    user_details: false,
    edukan :false,
    cancelled_services:false,
    plan:false,
    api_settings : false,
    payable: false,
    receivable: false,
};
